apiVersion: v1
kind: Pod
metadata:
  name: pvc-mount-pod
spec:
  containers:
  - name: pvc-container
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "tail -f /dev/null"]  # Keep the container running
    volumeMounts:
    - name: pvc-volume
      mountPath: /mnt  # Change this to the mount path of your PVC
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: schemaspy  # Replace with your PVC name