name: Dev Env - Test + Build Pipeline

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  codeql-scan:
      name: codeql-scan
      runs-on: ubuntu-latest
      permissions:
        actions: read
        contents: read
        security-events: write

      strategy:
        fail-fast: false
        matrix:
          language: [ 'python' ]

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{ secrets.OPENSHIFT_LOGIN_REGISTRY }} --token=${{ secrets.OPENSHIFT_SA_TOKEN_DEV }}

      - name: Switch to correct project environment in Openshift
        shell: bash
        run: |
          oc project ${{ secrets.OPENSHIFT_NAMESPACE_DEV }}

      - name: Build image on OpenShift
        shell: bash
        run: |
          oc start-build ${{ secrets.OPENSHIFT_BUILDCONFIG }}
